# Generated by Django 3.2.9 on 2021-12-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_auto_20211220_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('turno', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Vendedores',
        ),
    ]
