# Generated by Django 3.2.9 on 2021-12-22 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_auto_20211221_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='codCliente',
        ),
    ]
