# Generated by Django 3.2.9 on 2021-12-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_remove_clientes_codcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
