# Generated by Django 3.2.9 on 2021-12-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_alter_clientes_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('consulta', models.CharField(max_length=150)),
            ],
        ),
    ]
